name: test

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  golangci:
    name: coverage and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
      - name: go coverage
        run: |
          go test -mod=vendor -v -race -covermode=atomic -coverprofile=coverage.out ./...
      - uses: codecov/codecov-action@v2
        if: success()
        with:
          file: ./coverage.out
          flags: sretools_tests
          name: sre-tools tests
